CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(160) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_usuario_correo UNIQUE (correo),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('PROFESIONAL', 'ENCARGADO')),
    CONSTRAINT ck_usuario_correo_formato CHECK (correo ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

CREATE TABLE participante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id BIGINT NOT NULL REFERENCES usuario(id),
    encargado_id BIGINT NOT NULL REFERENCES usuario(id),
    nombre VARCHAR(120) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_participante_fecha_nacimiento CHECK (fecha_nacimiento <= CURRENT_DATE),
    CONSTRAINT ck_participante_responsables_distintos CHECK (profesional_id <> encargado_id)
);

CREATE TABLE rutina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participante_id BIGINT NOT NULL REFERENCES participante(id),
    nombre VARCHAR(120) NOT NULL,
    hora_inicio TIME NOT NULL,
    vigencia_desde DATE NOT NULL,
    vigencia_hasta DATE,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    publicado_en TIMESTAMPTZ,
    CONSTRAINT ck_rutina_estado CHECK (estado IN ('BORRADOR', 'PUBLICADA', 'ARCHIVADA')),
    CONSTRAINT ck_rutina_vigencia CHECK (vigencia_hasta IS NULL OR vigencia_desde <= vigencia_hasta),
    CONSTRAINT ck_rutina_publicacion CHECK (
        (estado = 'PUBLICADA' AND publicado_en IS NOT NULL)
        OR (estado <> 'PUBLICADA')
    )
);

CREATE TABLE rutina_dia_semana (
    rutina_id BIGINT NOT NULL REFERENCES rutina(id) ON DELETE CASCADE,
    dia_semana SMALLINT NOT NULL,
    PRIMARY KEY (rutina_id, dia_semana),
    CONSTRAINT ck_rutina_dia_semana CHECK (dia_semana BETWEEN 1 AND 7)
);

CREATE TABLE paso_rutina (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rutina_id BIGINT NOT NULL REFERENCES rutina(id) ON DELETE CASCADE,
    orden SMALLINT NOT NULL,
    descripcion VARCHAR(240) NOT NULL,
    duracion_estimada_min SMALLINT NOT NULL,
    pictograma VARCHAR(120),
    CONSTRAINT uk_paso_rutina_orden UNIQUE (rutina_id, orden),
    CONSTRAINT ck_paso_rutina_orden CHECK (orden > 0),
    CONSTRAINT ck_paso_rutina_duracion CHECK (duracion_estimada_min BETWEEN 1 AND 180)
);

CREATE TABLE ejecucion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rutina_id BIGINT NOT NULL REFERENCES rutina(id),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME,
    adherencia NUMERIC(5,2),
    estado VARCHAR(20) NOT NULL DEFAULT 'ABIERTA',
    registrado_por_id BIGINT NOT NULL REFERENCES usuario(id),
    cerrado_en TIMESTAMPTZ,
    CONSTRAINT uk_ejecucion_rutina_fecha UNIQUE (rutina_id, fecha),
    CONSTRAINT ck_ejecucion_fecha CHECK (fecha <= CURRENT_DATE),
    CONSTRAINT ck_ejecucion_estado CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT ck_ejecucion_horas CHECK (hora_fin IS NULL OR hora_fin >= hora_inicio),
    CONSTRAINT ck_ejecucion_adherencia CHECK (adherencia IS NULL OR adherencia BETWEEN 0 AND 100),
    CONSTRAINT ck_ejecucion_cierre CHECK (
        (estado = 'CERRADA' AND hora_fin IS NOT NULL AND adherencia IS NOT NULL AND cerrado_en IS NOT NULL)
        OR (estado = 'ABIERTA')
    )
);

CREATE TABLE registro_paso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ejecucion_id BIGINT NOT NULL REFERENCES ejecucion(id) ON DELETE CASCADE,
    paso_rutina_id BIGINT NOT NULL REFERENCES paso_rutina(id),
    resultado VARCHAR(20) NOT NULL,
    observacion_corta VARCHAR(240),
    registrado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_registro_paso_ejecucion_paso UNIQUE (ejecucion_id, paso_rutina_id),
    CONSTRAINT ck_registro_paso_resultado CHECK (resultado IN ('LOGRADO', 'CON_APOYO', 'NO_LOGRADO'))
);

CREATE INDEX idx_participante_profesional ON participante(profesional_id);
CREATE INDEX idx_participante_encargado ON participante(encargado_id);
CREATE INDEX idx_rutina_participante_estado ON rutina(participante_id, estado);
CREATE INDEX idx_rutina_vigencia ON rutina(vigencia_desde, vigencia_hasta);
CREATE INDEX idx_paso_rutina_rutina_orden ON paso_rutina(rutina_id, orden);
CREATE INDEX idx_ejecucion_rutina_fecha ON ejecucion(rutina_id, fecha DESC);
CREATE INDEX idx_ejecucion_registrado_por ON ejecucion(registrado_por_id);
CREATE INDEX idx_registro_paso_paso ON registro_paso(paso_rutina_id);

COMMENT ON TABLE usuario IS 'Usuarios que operan SIRA: profesionales y encargados.';
COMMENT ON TABLE participante IS 'Personas que siguen rutinas; no inician sesion en el sistema.';
COMMENT ON TABLE rutina IS 'Plantilla transaccional de una rutina asignada a un participante.';
COMMENT ON TABLE rutina_dia_semana IS 'Dias de la semana en que aplica una rutina, normalizados para evitar listas dentro de rutina.';
COMMENT ON TABLE paso_rutina IS 'Pasos ordenados que componen una rutina.';
COMMENT ON TABLE ejecucion IS 'Instancia diaria de una rutina ejecutada en casa o en el centro.';
COMMENT ON TABLE registro_paso IS 'Resultado de cada paso dentro de una ejecucion.';
